### ISSUE TITLE
Could you share the "women  data" mentioned in the code?

### ISSUE THREAD

**Issue by GaoPeng97** [lynnna-xu/text-generation-transformer#1]

**Comment by Haitons** [comment]
Have you got the data now? I need it, too.

**Comment by linWujl** [comment]
Do you have the data used in the code, thank you. I make some fake data, but got the error:
Traceback (most recent call last):
  File "transformer_generator.py", line 520, in <module>
    filter_pred=lambda x: len(vars(x)['src']) <= MAX_LEN and
  File "/home/lin.wjl/anaconda2/envs/python3/lib/python3.6/site-packages/torchtext/data/dataset.py", line 78, in splits
    os.path.join(path, train), **kwargs)
  File "/home/lin.wjl/anaconda2/envs/python3/lib/python3.6/site-packages/torchtext/data/dataset.py", line 281, in __init__
    super(TabularDataset, self).__init__(examples, fields, **kwargs)
  File "/home/lin.wjl/anaconda2/envs/python3/lib/python3.6/site-packages/torchtext/data/dataset.py", line 44, in __init__
    examples = list(examples)
  File "transformer_generator.py", line 520, in <lambda>
    filter_pred=lambda x: len(vars(x)['src']) <= MAX_LEN and
KeyError: 'src'

**Comment by shashankMadan-designEsthetics** [comment]
https://www.kaggle.com/nicapotato/womens-ecommerce-clothing-reviews 
you can just take this data but i get a problem with dim=-1 need to check on that

**Comment by mmaher22** [comment]
@shashankMadan-designEsthetics  What is the source and target in this case?

**Comment by Tursunali-Kholdorov** [comment]
> 
@shashankMadan-designEsthetics
This is not the right dataset. The author used chinese data.
